--- 
env: 
  global: 
  - secure: |-
      MEMMhUuO0zhM7csUCl0LeKYH2ivh4X7jKpmA4p1MQdzM495p9+bqWHCIHh9H
      b+XlNrzkBK/aa/PyEz0DuuwKOgD5Qwxe53C9jS7Sh/WIKsodRXBy5Qdr+3eH
      A05zfj8Q4a8Wqq8EjvFq6iX0MGRYFzqjtxCpe4OoAAVukVH/6B4=
  - secure: |-
      IWRRBADq+SleAxxxbUgXkdn+x9vOypZdf0gG6p1DLDaBQNseD88GoguaIlV6
      ZCIpu/KHV6xdfTjL8gkqePuE7pfVTT8X7Qpg2JlzGpUcwX/KssXy+xxtWDvM
      MycmNpq412bqSRckYWPypxSje47Hn3t3sNdznxrxD1azd3Lu/8s=
language: scala
scala: 
- 2.10.2
- 2.10.1
- 2.10.0
- 2.9.3
